// Script to download all Minion Masters card images from the wiki
const fs = require('fs');
const path = require('path');

// All card names extracted from the wiki (318 total)
const cardNames = [
  '"Armored" Scrats',
  'A\'Zog, Voidfiend of Shars\'Rakk',
  'A.I.M. Bot',
  'Adventuring Party',
  'Akinlep\'s Gong of Pestilence',
  'An\'Kahesh, Desert\'s Doom',
  'Annihilator',
  'Arcane Barrage',
  'Arcane Bolt',
  'Arcane Golem',
  'Arcane Missiles',
  'Arcane Ring',
  'Ardent Aegis',
  'Armored Escort',
  'Assassin',
  'Backpack Salesman',
  'Banner of the Legion',
  'Banner of the Swamp',
  'Bao\'s Technique',
  'Barbarian Miner',
  'Bahra the Fist',
  'Barrier Guard',
  'Battle Shrine',
  'Beast Master',
  'Big Bertha',
  'Big Pharma Doge',
  'Black Hole',
  'Blade Runner',
  'Blood Imp',
  'Blood Lunar Acolyte',
  'Blood Lunar Cultist',
  'Blood Sacrificial Circle',
  'Blood Seeker',
  'Blood Sacrifice',
  'Bloodborne Imp',
  'Bloodlust',
  'Blue Golem',
  'Bone Crusher',
  'Bone Lord',
  'Bone Minions',
  'Book of the Keeper',
  'Boom Buggy',
  'Bounty Hunter',
  'Bravebeard',
  'Bred Purebloods',
  'Bridge Buddies',
  'Brutus',
  'Buccaneer',
  'Burn',
  'Call to Arms',
  'Calm Down',
  'Cannon Mortar',
  'Cannon Roller',
  'Captain O\'Hearty',
  'Caretaker',
  'Carrion Legion',
  'Chain Lightning',
  'Chaos Imp',
  'Charge',
  'Chimaera',
  'Circle of Fire',
  'Cleaver',
  'Clone of Milloween',
  'Clone of Mordar',
  'Clone of Ratbo',
  'Clone of Ravager',
  'Clone of Settsu',
  'Clone of Stormbringer',
  'Clone of Valorian',
  'Clone of Volco',
  'Colossus',
  'Combustion',
  'Concussive Blast',
  'Corrupted Crystal Mancer',
  'Crossbow Dudes',
  'Crystal Archers',
  'Crystal Baron',
  'Crystal Bomb',
  'Crystal Cannon',
  'Crystal Construct',
  'Crystal Elemental',
  'Crystal Elf Mage',
  'Crystal Golems',
  'Crystal Hive Guard',
  'Crystal Mancer',
  'Crystal Sentinel',
  'Crystal Shard',
  'Crystal Volley',
  'Cursed Banner',
  'Cursed Fanatic',
  'Cursed Totem',
  'Cycloptic Monk',
  'Daemon',
  'Dark Ritual',
  'Dead Ringer',
  'Defenso Chopper',
  'Demon of Darkness',
  'Deviltry',
  'Diamond Guard',
  'Diona\'s Prophet',
  'Dire Wolf',
  'Divine Blessing',
  'Divine Guardian',
  'Divine Warrior',
  'Draconic Fire',
  'Dragon Lord',
  'Dragon Nest',
  'Drumlin',
  'Dust Devil',
  'Dust Shot',
  'Dwarfmancer',
  'Dwarven Armored Unit',
  'Earth Golem',
  'Earthshaker',
  'Echo Blast',
  'Electro Wizard',
  'Elemental Swarm',
  'Elemental Totem',
  'Enlighted Paladin',
  'Eruption',
  'Essence of Apep',
  'Evangelist',
  'Evil Empyrean',
  'Evil Knight',
  'Executioner',
  'Faith',
  'Fallen Morellia',
  'Fanatic',
  'Fearless Militia',
  'Fire Bat',
  'Fire Bomb',
  'Fire Elemental',
  'Fire Emblem',
  'Fire Imp',
  'Fire Rain',
  'Fire Shaman',
  'Fire Spirit',
  'Fireball',
  'Firebomb',
  'Firefist',
  'Flame Bomb',
  'Flame Spirit',
  'Flaming Doge',
  'Footmen',
  'Frenzy',
  'Frozen Trap',
  'Frogwalker',
  'Gahan the Stone Lord',
  'Ghosted Demon',
  'Giant Slayer',
  'Glory Knight',
  'Glory Sword',
  'Golden Armored Golem',
  'Golem of Rage',
  'Goliath',
  'Great Ram',
  'Grenadier',
  'Griffin',
  'Gryphon Rider',
  'Guardian',
  'Guided Strike',
  'Gunslinger',
  'Harbinger',
  'Healing Shrine',
  'Healing Totem',
  'Healer Bot',
  'Health Collector',
  'Heavy Crossbowman',
  'Heavy Guardian',
  'Hell Rocket',
  'Hell Spitter',
  'Horde of Scrats',
  'Howling Moon',
  'Hunter',
  'Hunting Pack',
  'Ice Bomb',
  'Ice Dragon',
  'Ice Shard',
  'Ice Wall',
  'Imp Swarm',
  'Impulse',
  'Incubus',
  'Inferno Bot',
  'Inferno Legion',
  'Inferno Vortex',
  'Iron Loader',
  'Iron Wyrm',
  'Javelin Thrower',
  'Jester',
  'Kalthar the Seeker',
  'Knight of the Dawn',
  'Last Stand',
  'Legacy Healing Totem',
  'Legacy Iron Loader',
  'Legion',
  'Legion Legionnaire',
  'Life Bomb',
  'Lightning Bolt',
  'Lightning Gust',
  'Limnal Bomb',
  'Living Statue',
  'Lunatic',
  'Mad Hunter',
  'Mage',
  'Magic Bomb',
  'Magma Storm',
  'Mana Crystal',
  'Mana Scythe',
  'Mana Storm',
  'Marksrat',
  'Massy Golem',
  'Master Apep',
  'Master Assassin',
  'Master Stormancer',
  'Master Zoey',
  'Mechanical Samurai',
  'Medic',
  'Mending',
  'Merc',
  'Might Of Apep',
  'Milloween\'s Ritual',
  'Morellia\'s Zealot',
  'Mortar',
  'Mountain Legion',
  'Mourningstar',
  'Myrmidon',
  'Necrobeast',
  'Necromancer',
  'Necromancers',
  'Nine Tail',
  'Nova',
  'Obsidian Golem',
  'Ogre',
  'Old Beresad',
  'Old One',
  'Oracle',
  'Overcharge',
  'Paladin',
  'Paralyze',
  'Phalanx',
  'Phantom Warrior',
  'Phoenix',
  'Piercing Missiles',
  'Piercing Throw',
  'Plagued Construct',
  'Plasma Marines',
  'Poison Golem',
  'Portal Vortex',
  'Possession',
  'Power Totem',
  'Pride Herald',
  'Protector',
  'Pterodactyl',
  'Puffy',
  'Purifier',
  'Pyrotech',
  'Pyrotechnic Engineer',
  'Rage',
  'Rampage',
  'Ratbo\'s Command',
  'Ratbo\'s Scrap Pack',
  'Ravager\'s Rampage',
  'Ravager\'s Vanguard',
  'Ravager\'s Wolf Pack',
  'Reaper',
  'Red Golem',
  'Reinforcements',
  'Relentless',
  'Replicate',
  'Resilience',
  'Resurrection',
  'Retribution',
  'Return to Earth',
  'Revenge',
  'Ring of Fire',
  'Ritual of Strength',
  'Ritual of Summoning',
  'Rocket Loader',
  'Rocket Raider',
  'Royal Guard',
  'Sacrifice',
  'Samurai',
  'Screaming Scrat',
  'Scrat Brigade',
  'Scrat Mob',
  'Scrat Pack',
  'Scrat Swarm',
  'Scrat Tank',
  'Scrat',
  'Scrataur',
  'Scrats',
  'Screamer',
  'Scout',
  'Seed of Corruption',
  'Septicemic',
  'Serene Monk',
  'Settsu\'s Flying Dagger',
  'Settsu\'s Shadow Step',
  'Settsu\'s Wind Walk',
  'Shadow Cloak',
  'Shadow Legion',
  'Shadowbolt',
  'Shadowcaster',
  'Shadowflame',
  'Shadowmancer',
  'Shadowstep',
  'Shark Lancer',
  'Shield Guard',
  'Shield Wall',
  'Shield',
  'Shielded Knight',
  'Shock Rock',
  'Shock',
  'Shout',
  'Skeletal Dragon',
  'Skeletal Legion',
  'Skeleton Archer',
  'Skeleton Army',
  'Skeleton Horde',
  'Skeleton',
  'Slayer',
  'Slither Lords',
  'Snake Legion',
  'Sniper',
  'Snow Crystal',
  'So Much Rat',
  'Soldier',
  'Soul Stealer',
  'Soul Storm',
  'Space Suit',
  'Spawn of Apep',
  'Spear Thrower',
  'Spectral Warrior',
  'Spell Trap',
  'Spirit Vessel',
  'Spiritmancer',
  'Split Terror',
  'Stabby',
  'Stab Totem',
  'Star Vanguard',
  'Star Viper',
  'Steel Golem',
  'Stone Launcher',
  'Stonewall',
  'Stormbringer\'s Overcharge',
  'Stonerider',
  'Stormy',
  'Strike',
  'Sunder',
  'Sunburst',
  'Supersonic',
  'Support',
  'Swarm of Bats',
  'Swarmers',
  'Tank',
  'Telekinesis',
  'Teleport',
  'The Throne of Apep',
  'Tome of Insight',
  'Totem of Control',
  'Totem of Healing',
  'Totem of Power',
  'Toxic Bomb',
  'Trapper',
  'Trigger',
  'Tunnel Rat',
  'Two-Handed Warrior',
  'Unearthed Golem',
  'Undead Legion',
  'Undead Priest',
  'Undead Warrior',
  'Valorian\'s Blessing',
  'Valorian\'s Pillar',
  'Valorian\'s Radiance',
  'Vampire',
  'Vampire Lord',
  'Vengeful Knight',
  'Vicious Strike',
  'Void Knight',
  'Void Walker',
  'Void Warp',
  'Volco\'s Earthfire',
  'Volco\'s Explosion',
  'Volco\'s Mine',
  'Wall Breaker',
  'War Banner',
  'War Beast',
  'War Machine',
  'Warmage',
  'Warrior',
  'Weakness',
  'Werewolf',
  'White Golem',
  'Wild Pack',
  'Wing Warrior',
  'Wizard',
  'Wolf',
  'Wooden Knight',
  'Xiao Long',
  'Zealot',
  'Zombie'
];

// Function to convert card name to URL-safe format
function nameToUrl(name) {
  return name.replace(/'/g, '%27').replace(/"/g, '%22').replace(/ /g, '_');
}

// Function to convert card name to filename
function nameToFilename(name) {
  return name.toLowerCase()
    .replace(/['"]/g, '')
    .replace(/[^a-z0-9]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// Output the card mapping for download
const cardMappings = cardNames.map(name => ({
  name: name,
  url: `https://minionmasters.fandom.com/wiki/${nameToUrl(name)}`,
  filename: `${nameToFilename(name)}.png`
}));

console.log('Card mappings generated:');
console.log(`Total cards: ${cardMappings.length}`);
console.log('First 10 cards:');
cardMappings.slice(0, 10).forEach(card => {
  console.log(`${card.name} -> ${card.filename}`);
});

module.exports = { cardMappings, cardNames };